server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: smart hospital
  datasource:
    url: jdbc:mysql://localhost:3306/smart_hospital?useUnicode=true&characterEncoding=UTF-8
    username: #username
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.team10.smarthospital.model
  configuration:
    mapUnderscoreToCamelCase: true
